---
title: "kableExtra test"
author: "Kevin L. Stierhoff"
date: "9/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(knitr, kableExtra)
```

```{r}

dt <- mtcars[1:5, 1:6]

kbl(dt, format = 'latex', booktabs = FALSE, escape = FALSE,
          align           = c(rep("l", 3), rep("r",ncol(dt) - 2)),
          digits          = c(0),
          format.args     = list(big.mark = ",")) %>% 
      kable_styling(latex_options = c("scale_down"),
                    position = "center",
                    font_size = 8) %>%
      column_spec(1, italic = T) %>% 
      collapse_rows(columns = 1:3) 

# kable(be.table.sub, format = knitr.format, booktabs = TRUE, escape = FALSE,
#           align           = c(rep("l", 3), rep("r",ncol(be) - 2)),
#           digits          = c(0),
#           format.args     = list(big.mark = ","),
#           caption = '(ref:biomass-anch-n)') %>% 
#       kable_styling(latex_options = c("striped","hold_position","scale_down"),
#                     position = "center",
#                     font_size = 8) %>%
#       column_spec(1, italic = T) %>% 
#       collapse_rows(columns = c(1:3)) %>%
#       # row_spec(bold.rows, bold = TRUE) %>%
#       add_header_above(c("Species" = 2, "Stratum" = 5, "Trawl" = 2, "Biomass" = 4)) 


# %>%
#       # row_spec(bold.rows, bold = TRUE) %>%
#       add_header_above(c("Species" = 2, "Stratum" = 5, "Trawl" = 2, "Biomass" = 4)) 
```

