---
title: "Map Saildrone overlap to assist Echoview processing"
author: "Kevin Stierhoff"
date: '`r format(Sys.time(), format = "%F %T", tz = "UTC", usetz = TRUE)`'
output: html_document
---

```{r setup, include=FALSE}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,lubridate,here,fs,sf,mapview,DT)

# Install and load required packages from Github -------------------------------
# surveyR
pacman::p_load_gh("kstierhoff/surveyR")
# atm
pacman::p_load_gh("kstierhoff/atm")
# rnaturalearth data
pacman::p_load_gh("ropenscilabs/rnaturalearthdata")
pacman::p_load_gh("ropenscilabs/rnaturalearthhires")

# Get nav from ERDDAP
get.nav    <- T
nav.source <- "ERDDAP"
get.nav.sd <- T

# Other settings
resize.map <- F # Resize map during survey; if T, uses anticipated bounds of survey area

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, 
  fig.align = "center", dev = "png", dev.args = list(type = "cairo"), dpi = 150)
```

```{r user-input,echo=FALSE}
# Saildrone numbers to include
saildrone.list <- c(1076, 1077)
type.list <- c("Adaptive", "Compulsory")

# Get project name from directory
prj.name <- last(unlist(str_split(here(), "/")))

# Get all settings files
settings.files <- dir(here("Doc/settings"))

# Source survey settings file
prj.settings <- settings.files[str_detect(settings.files, paste0("settings_", prj.name, ".R"))]
source(here("Doc/settings", prj.settings))
```

# Load Lasker NASC data  

```{r load-nasc,include=FALSE,message=FALSE}
# Load backscatter data
load(here("Data/Backscatter/nasc_all.Rdata"))

# Remove bad intervals
nasc <- nasc %>% 
  filter(lat != 999, long != 999)
```


```{r process-nav,include=FALSE,message=FALSE}
# Source code to get nav data from ERDDAP or SCS
if (nav.source == "ERDDAP") {
  source(here("Code/get_nav_erddap.R"))
} else if (nav.source == "SCS") {
  source(here("Code/get_nav_scs.R"))
}

# Read transect waypoints
wpts <- read_csv(here("Data/Nav", wpt.filename))

# Convert planned transects to sf; CRS = crs.geog
wpts.sf <- wpts %>% 
  filter(Type %in% wpt.types) %>% 
  st_as_sf(coords = c("Longitude","Latitude"), crs = crs.geog) %>% 
  mutate(
    label    = paste("Transect", Transect),
    popup    = paste('<b>Transect:</b>', Transect, Type)
  )

transects.sf <- wpts.sf %>% 
  group_by(Type, Transect, Region) %>% 
  summarise(do_union = F) %>% 
  st_cast("LINESTRING") %>% 
  ungroup() %>% 
  mutate(
    distance = round(as.numeric(st_length(.))/1852,1),
    label    = paste("Transect", Transect),
    popup    = paste('<b>Transect:</b>', Transect, Type, '<br/>',
                       'Distance:', distance, 'nmi<br/>')
  )

# Create gps.csv file from nav to replace missing data in Echoview
nav.gps <- nav %>% 
      mutate(GPS_date = format(time, format = "%F"),
             GPS_time = format(time, format = "%T")) %>% 
      select(GPS_date, GPS_time, latitude = lat, longitude = long)

write_csv(nav.gps, here("Output/nav.gps.csv"))

# Get most recent vessel position for plotting
nav.now <- tail(nav.sf, 1) %>% 
  mutate(label = paste("Last position:", time, "UTC"),
         popup = paste0('<b>Vessel name: </b>', survey.vessel, '<br/>',
                        '<b>Last position: </b>', time, ' UTC<br/>'))

# Set padding around data  
if (resize.map) {
  # Use nav data to resize map to survey progress
  map.bounds <- nav.paths.sf %>% 
    st_transform(crs = crs.proj) %>%
    st_bbox()  
} else {
  # Use nav data to resize map to survey progress
  map.bounds <- transects.sf %>%
    st_transform(crs = crs.proj) %>%
    st_bbox()  
}
```


# Load Saildrone tracks from ERDDAP

```{r get-saildrone-nav,include=FALSE,message=FALSE}
if (get.nav.sd) {
   # Load existing nav data
  if (file.exists(here("Data/Nav/nav_data_saildrone.Rdata"))) {
    load(here("Data/Nav/nav_data_saildrone.Rdata"))
    
    # Calculate difference between max nav time and now
    nav.lag.sd <- difftime(now(tzone = "UTC"), max(ymd_hms(nav.sd$datetime)), units = "hours")
    
    # Get new erddap start date from max date
    erddap.survey.start.sd <- paste0(format(max(date(nav.sd$time)), ""), "T00%3A00%3A00Z")
  } else {
    nav.lag.sd <- 24
  }
  
  if (get.nav) {
    # Update only every 24 h to reduce processing time, especially at sea
    if (nav.lag.sd >= 24) {
      # Generate ERDDAP URL
      saildroneURL <- URLencode(paste0(
        erddap.url.sd, ".csv0?", erddap.vars.sd,
        "&time%3E=", erddap.survey.start.sd, "&time%3C=", erddap.survey.end.sd))
      
      # Download and parse ERDDAP nav data
      nav.temp.sd <- data.frame(read.csv(saildroneURL, header = F, 
                                         colClasses = erddap.classes.sd, 
                                         row.names = NULL, skip = 0))
      names(nav.temp.sd) <- erddap.headers.sd
      
      # Filter to remove bad SST values
      nav.temp.sd <- nav.temp.sd %>% 
        mutate(datetime = ymd_hms(time)) %>%
        filter(!is.nan(lat), !is.nan(long)) %>%
        filter(long != 0, lat != 0)
      
      # Append new nav data
      if (exists("nav.sd")) {
        nav.sd <- bind_rows(nav.sd, nav.temp.sd) %>% 
          distinct()
      } else {
        nav.sd <- nav.temp.sd
      }
    }
    
    # Convert saildrone nav to spatial
    nav.sd.sf <- st_as_sf(nav.sd, coords = c("long","lat"), crs = crs.geog)
    
    # Get most recent vessel position for plotting
    nav.now.sd <- nav.sd.sf %>% 
      group_by(saildrone) %>% 
      slice(n()) %>% 
      mutate(label = paste("Saildrone", saildrone, "Last position:", datetime, "UTC"),
             popup = paste0('<b>Saildrone: </b>', saildrone, '<br/>',
                        '<b>Last position: </b>', datetime, ' UTC<br/>'))
    
    # Convert saildrone nav to spatial
    nav.sd.paths.sf <- nav.sd.sf %>% 
      group_by(saildrone) %>% 
      summarise(do_union = F) %>% 
      st_cast("LINESTRING") %>% 
      mutate(tracklength = st_length(.))

    # Save nav data
    save(nav.sd, nav.sd.sf, nav.sd.paths.sf, nav.now.sd, 
         file = here("Data/Nav/nav_data_saildrone.Rdata"))
    
    # Create gps.csv files from ERDDAP data
    for (i in unique(nav.sd$saildrone)) {
      saildrone.gps <- filter(nav.sd, saildrone == i) %>% 
        mutate(GPS_date = format(datetime, format = "%F"),
               GPS_time = format(datetime, format = "%T")) %>% 
        select(GPS_date, GPS_time, latitude = lat, longitude = long)
      
      write_csv(saildrone.gps, here("Output", paste(i, "_erddap.gps.csv", sep = "")))
    }
  } else {
    # Load nav data
    load(here::here("Data/Nav/nav_data_saildrone.Rdata"))
  }
}
```

```{r export-gps-csv}
# Export Saildrone nav as gps.csv for Echoview processing
for (i in unique(nav.sd$saildrone)) {
  gps.tmp <- filter(nav.sd, saildrone == i) %>% 
    mutate(GPS_fix = seq(1,n()),
           GPS_date = format(datetime, format = "%D"),
           GPS_time = format(datetime, format = "%T")) %>% 
    select(GPS_fix, GPS_date, GPS_time, Latitude = lat, Longitude = long)
  
  write_csv(gps.tmp, here("Output", paste0("saildrone_", i,".gps.csv")))
}
```

```{r restrict-data,message=FALSE}
# Select only Saildrones in our analysis and restrict data to date range 
# to eliminate transits
nav.sd <- nav.sd %>% 
  filter(saildrone %in% saildrone.list) %>% 
  mutate(datetime = datetime + hours(sd.time.offset), # Apply time adjustment, if necessary
         date     = date(datetime)) 
```

# Convert Lasker data to spatial and buffer

```{r process-lasker,message=FALSE}
# Convert Lasker transects to lines
tx.lines <- nasc %>% 
  arrange(vessel.name, long) %>% 
  st_as_sf(coords = c("long","lat"),crs = 4326) %>% 
  group_by(transect.name) %>% 
  summarise(do_union = F) %>% 
  st_cast("LINESTRING") %>% 
  filter(str_detect(transect.name, "RL"))

# Buffer lines by 3 nmi
tx.buffer <- transects.sf %>% 
  st_buffer(dist = 3/60)

# # View result of buffering
# mapview(tx.buffer, zcol = "Type", alpha.regions = 0.1) + 
#   mapview(tx.lines, color = "black", legend = FALSE)
```

# Downsample Saildrone nav and convert to spatial

```{r process-saildrone}
# Create saildrone lines
sd.lines <- nav.sd %>% 
  st_as_sf(coords = c("long","lat"), crs = 4326) %>% 
  group_by(saildrone) %>% 
  summarise(do_union = F) %>% 
  st_cast("LINESTRING") %>% 
  mutate(saildrone = as.character(saildrone))

# Convert Saildrone points to sf and downsample
sd.sf <- nav.sd %>% 
  mutate(date = date(datetime),
         hour = hour(datetime)) %>% 
  # mutate(datetime = ymd_hms(time),
  #        date = date(datetime),
  #        hour = hour(datetime)) %>% 
  group_by(saildrone, date, hour) %>% 
  slice(1) %>% 
  st_as_sf(coords = c("long","lat"), crs = 4326)

# View Saildrone transects relative to transect buffers
# mapview(tx.buffer, zcol = "Type", alpha.regions = 0.1) +
#   mapview(sd.lines)
```

# Plot all Saildrone transects

```{r map-saildrone-all}
# mapview(tx.buffer, zcol = "Type", alpha.regions = 0.1) + 
#   mapview(sd.lines, zcol = "saildrone") +
#   mapview(sd.sf, zcol = "saildrone")
```

# Intersect Saildrone with planned transect buffers

```{r intersect-nav,message=FALSE}
# Get intersection of Saildrone and Lasker nav
sd.intersection <- sd.sf %>% 
  st_intersection(filter(tx.buffer, Type %in% type.list))

# mapview(tx.buffer, zcol = "Type", alpha.regions = 0.1) + 
#   # mapview(sd.lines, zcol = "saildrone") +
#   mapview(sd.intersection, zcol = "saildrone")
```

# Summarize intersecting Saildrone data

```{r summarize-saildrone}
# sd.int.summary <- sd.intersection %>% 
#   group_by(saildrone, label) %>% 
#   summarise(
#     n = n(),
#     min.date = min(datetime),
#     max.date = max(datetime),
#     duration = difftime(max.date, min.date, units = "hours")
#   ) %>% 
#   st_set_geometry(NULL)
# 
# sd.intersection <- sd.intersection %>% 
#   left_join(select(sd.int.summary, saildrone, label, min.date)) %>% 
#   mutate(time.diff = difftime(datetime, min.date, units = "hours")) %>% 
#   filter(as.numeric(time.diff) <= 100) %>% 
#   arrange(saildrone, datetime)


# Summarise resulting data
sd.summary <- sd.intersection %>% 
  filter(saildrone %in% saildrone.list) %>% 
  group_by(saildrone, label) %>% 
  summarise(
    n = n(),
    min.date = min(datetime),
    max.date = max(datetime),
    duration = difftime(max.date, min.date, units = "hours")
  ) %>% 
  mutate(min.date = format(min.date, "%F %T", tz = "UTC"),
         max.date = format(max.date, "%F %T", tz = "UTC")) %>% 
  arrange(desc(label)) %>% 
  st_set_geometry(NULL)

# View all data
# DT::datatable(sd.summary)
```

# Filter Saildrone data

```{r filter-saildrone}
sd.final <- sd.summary %>% 
  arrange(saildrone, min.date) %>% 
  filter(duration > 6)

DT::datatable(sd.final)
```

# Intersect filtered Saildrone with planned transect buffers

```{r intersect-nav-final,out.height='10in',out.width='100%'}
sd.int.final <- filter(sd.intersection, saildrone %in% saildrone.list) %>% 
  mutate(saildrone = as.character(saildrone))

mapview(sd.lines, zcol = "saildrone") + 
  mapview(filter(tx.buffer, Type %in% type.list), zcol = "Type", alpha.regions = 0.1) + 
  # mapview(sd.lines, zcol = "saildrone") +
  mapview(sd.int.final, zcol = "saildrone")
```




